from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader

def generate_booking_pdf(user, event):
    # Generates a PDF booking confirmation for a user and event
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Add UniGather logo to the PDF
    logo_path = "static/logoNormal.png"
    logo = ImageReader(logo_path)
    # Logo size & position (recommended)
    logo_width = 100
    logo_height = 100

    c.drawImage(
        logo,
        (width - logo_width) / 2,
        height - 150,   # move it DOWN closer to title
        width=logo_width,
        height=logo_height,
        mask="auto"
    )


    # PDF title and header line
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(
        width / 2,
        height - 280,
        "UniGather Booking Confirmation"
    )
    c.line(50, height - 300, width - 50, height - 300)

    # Booking details section
    y = height - 350
    details = [
        ("Event Name", event["event_name"]),
        ("Date", event["event_date"]),
        ("Time", event["event_time"]),
        ("Location", event["event_loc"]),
        ("Booked By", user.get("full_name", user.get("username", "User"))),
        ("Booking ID", event["id"]),
    ]

    # Render booking details onto the PDF
    for label, value in details:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(70, y, f"{label}:")
        c.setFont("Helvetica", 12)
        c.drawString(200, y, str(value))
        y -= 30

    # Footer text
    c.setFont("Helvetica", 9)
    c.drawCentredString(
        width / 2,
        40,
        "Generated by UniGather • IN3046 Cloud Computing Project"
    )

    c.showPage()
    c.save()

    # Reset buffer position for download
    buffer.seek(0)
    return buffer

